Fix permission denied issue during Package external libraries
gitx/objective-git pull request #1
Opened 2018-12-21 19:44 UTC by carlbrown

This happens because `libssl.1.0.0.dylib` is installed mode 444 from Homebrew in /usr/local/lib
(or at least was on my brand new Mojave install).  So when `FileUtils.cp` makes a copy of it,
it stays readonly, so `install_name_tool` fails:

```
note: Packaging libcrypto.1.0.0.dylib…
warning: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib already in Frameworks directory, removing
note: Copying /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib to TARGET_FRAMEWORKS_PATH
note: Packaging libssl.1.0.0.dylib…
warning: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib already in Frameworks directory, removing
note: Copying /usr/local/opt/openssl/lib/libssl.1.0.0.dylib to TARGET_FRAMEWORKS_PATH
note: Fixing libcrypto.1.0.0.dylib install_name id…
note: Fixing libssl.1.0.0.dylib install_name id…
error: install_name_tool: can't open input file: /Users/carlb/Library/Developer/Xcode/DerivedData/GitX-ceopxklkteyyvrepxlzprsjsdegg/Build/Products/Debug/ObjectiveGit.framework/Versions/A/Frameworks/libssl.1.0.0.dylib for writing (Permission denied)
error: install_name_tool: can't lseek to offset: 0 in file: /Users/carlb/Library/Developer/Xcode/DerivedData/GitX-ceopxklkteyyvrepxlzprsjsdegg/Build/Products/Debug/ObjectiveGit.framework/Versions/A/Frameworks/libssl.1.0.0.dylib for writing (Bad file descriptor)
error: install_name_tool: can't write new headers in file: /Users/carlb/Library/Developer/Xcode/DerivedData/GitX-ceopxklkteyyvrepxlzprsjsdegg/Build/Products/Debug/ObjectiveGit.framework/Versions/A/Frameworks/libssl.1.0.0.dylib (Bad file descriptor)
error: install_name_tool: can't close written on input file: /Users/carlb/Library/Developer/Xcode/DerivedData/GitX-ceopxklkteyyvrepxlzprsjsdegg/Build/Products/Debug/ObjectiveGit.framework/Versions/A/Frameworks/libssl.1.0.0.dylib (Bad file descriptor)
error: install_name_tool failed with error pid 25708 exit 1:

```

2018-12-21 19:45 UTC, carlbrown commented
@tiennou

2019-01-22 01:58 UTC, nanotech requested changes

2019-01-22 01:58 UTC, nanotech commented on script/repackage-dylibs.rb
> +    FileUtils.chmod "u=wr", dep[:path]
This is `chmod`ing the wrong file; `dep[:path]` is the library's path in Homebrew. `chmod`ing the copied library would be

```ruby
FileUtils.chmod "u=wr", File.join(TARGET_FRAMEWORKS_PATH, dep.name)
```

2019-01-28 17:01 UTC, tiennou commented
This should be fixed with da034f6e7e82f2c4fae17488b08dd4154b60c974.

2019-01-28 17:01 UTC, closed without merging